inf_test=function(res.inf,LD,Theta,A){

if(is.vector(A)==T){
A=c(A)
Var2=matrixMultiply(LD,LD)
V=Theta
delta=1/sum(A*matrixVectorMultiply(V,A))
AAT=matrixMultiply(t(t(A)),t(A))/delta
P=V-matrixListProduct(list(V,AAT,V))
u=c(matrixVectorMultiply(V,res.inf))
u=sum(u*c(matrixVectorMultiply(Var2,u)))/2
PVar2=matrixMultiply(P,Var2)
e=sum(diag(PVar2))/2
h=sum(diag(matrixMultiply(PVar2,PVar2)))/2
kappa=h/2/e
v=2*e^2/h
}else{
if(length(A[1,])>1){
Var2=matrixMultiply(LD,LD)
V=Theta
AT=matrixMultiply(t(A),V)
P=V-matrixMultiply(t(AT),matrixMultiply(matrixGeneralizedInverse(matrixMultiply(AT,A)),AT))
u=c(matrixVectorMultiply(V,res.inf))
u=sum(u*c(matrixVectorMultiply(Var2,u)))/2
PVar2=matrixMultiply(P,Var2)
e=sum(diag(PVar2))/2
h=sum(diag(matrixMultiply(PVar2,PVar2)))/2
kappa=h/2/e
v=2*e^2/h
}

if(length(A[1,])==0){
Var2=matrixMultiply(LD,LD)
V=Theta
u=c(matrixVectorMultiply(V,res.inf))
u=sum(u*c(matrixVectorMultiply(Var2,u)))/2
VVar2=matrixMultiply(V,Var2)
e=sum(diag(VVar2))/2
h=sum(diag(matrixMultiply(VVar2,VVar2)))/2
kappa=h/2/e
v=2*e^2/h
}
}
pv=pchisq(u/kappa,v,lower.tail=F)
return(pv)
}
