matrixsqrt=function(A){
  fit=matrixEigen(A)
  d=fit$value
  d1=d*0
  d1[d>0]=1/d[d>0]
  d=sqrt(d)
  d1=sqrt(d1)
  A=matrixMultiply(fit$vector,t(fit$vector)*d)
  B=matrixMultiply(fit$vector,t(fit$vector)*d1)
  C=list(w=A,wi=B,eigenfit=fit)
  return(C)
}
